version: '3.8'

name: minitwitter
services:
    loadbalancer:
        image: nginx
        container_name: loadbalancer
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - '80:80'
        restart: always
        networks:
            - minitwitter
    db:
        container_name: db
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: supersecret123
            POSTGRES_DB: minitwitter
        volumes:
            - minitwitter-db:/var/lib/postgresql/data
        networks:
            - minitwitter
        restart: always

    api-1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-1
        image: spoonersl/minitwitter
        environment:
            DATABASE_URL: postgressql://postgres:supersecret123@db:5432/minitwitter
            OLLAMA_BASE_URL: http://ollama-1:11434
        depends_on:
            - db
        command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
        networks:
            - minitwitter
        restart: always

    api-2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-2
        image: spoonersl/minitwitter
        environment:
            DATABASE_URL: postgressql://postgres:supersecret123@db:5432/minitwitter
            OLLAMA_BASE_URL: http://ollama-1:11434
        depends_on:
            - db
        command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
        networks:
            - minitwitter
        restart: always

    app-1:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: app-1
        image: spoonersl/minitwitter-app
        environment:
            NUXT_PUBLIC_API_BASE_URL: http://localhost:80
        networks:
            - minitwitter
        restart: always

    ollama-1:
        container_name: ollama-1
        image: ollama/ollama
        ports:
            - '11434:11434'
        volumes:
            - minitwitter-ollama:/root/.ollama
        networks:
            - minitwitter
        restart: always

    redis:
        image: redis/redis-stack:latest
        container_name: redis
        ports:
            - '6379:6379'
            - '8001:8001'
        networks:
            - minitwitter
        restart: always

volumes:
    minitwitter-db:
    minitwitter-ollama:

networks:
    minitwitter:
        driver: bridge
