name: minitwitter
services:
    loadbalancer:
        image: nginx
        container_name: loadbalancer
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - '80:80'
        restart: 
            - always
    db:
        container_name: db
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: supersecret123
            POSTGRES_DB: minitwitter
        volumes:
            - ./docker-data/postgres:/var/lib/postgresql/data
        restart: always

    api-1:
        container_name: api-1
        image: spoonersl/minitwitter
        environment:
            DATABASE_URL: postgressql://postgres:supersecret123@db:5432/minitwitter
        depends_on:
            - db
        command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
        restart: always
    
    api-2:
        container_name: api-2
        image: spoonersl/minitwitter
        environment:
            DATABASE_URL: postgressql://postgres:supersecret123@db:5432/minitwitter
        depends_on:
            - db
        command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
        restart: always